/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @flow
 *
 * @generated by codegen project: GenerateViewConfigJs.js
 */

'use strict';

const NativeComponentRegistry = require('react-native/Libraries/NativeComponent/NativeComponentRegistry');
const { dispatchCommand } = require('react-native/Libraries/ReactNative/RendererProxy');

let nativeComponentName = 'DebuggingOverlay';

export const __INTERNAL_VIEW_CONFIG = {
  uiViewClassName: 'DebuggingOverlay',
  validAttributes: {},
};

export default NativeComponentRegistry.get(nativeComponentName, () => __INTERNAL_VIEW_CONFIG);

export const Commands = {
  highlightTraceUpdates(ref, updates) {
    dispatchCommand(ref, 'highlightTraceUpdates', [updates]);
  },

  highlightElements(ref, elements) {
    dispatchCommand(ref, 'highlightElements', [elements]);
  },

  clearElementsHighlights(ref) {
    dispatchCommand(ref, 'clearElementsHighlights', []);
  },
};
