source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '< 1.3.4'

# Ruby 3.4.0 has removed some libraries from the standard library.
# bigdecimal is included in Ruby 3.3.x, but required for older versions
gem 'bigdecimal' if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('3.3.0')
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
