import { describe, test, expect } from "bun:test";
import { createFixture, ZTS_BIN } from "./helpers";
import { resolve } from "node:path";

/**
 * Regression: Flow `component Name(ref?: ..., ...props) { ... }` 구문은 parser 단에서
 * `function Name_withRef(...) {}` + `const Name = React.forwardRef(Name_withRef)` 두
 * 문장을 담은 `flow_component_wrapper` 노드로 변환된다. semantic analyzer 의
 * `visitFlowComponentWrapper` 가 함수 부분만 순회하고 const_decl 부분은 건드리지 않아
 * 그 안의 `React` identifier_reference 가 `symbol_ids` 에 해석되지 않은 상태로 남았다.
 *
 * linker 의 `ns_member_rewrites` / `ns_inline_objects` 는 symbol_id 로 키잉되므로, 이
 * 미해결 identifier 들은 번들에서 `React` 그대로 emit 됐다. 해당 모듈의 hoisted var 에
 * `React` 선언이 없으면(linker 는 `__ns_N_0` 로 canonical 이름을 뒀으므로) 런타임에
 * `ReferenceError: Property 'React' doesn't exist`.
 *
 * 실 영향: react-native 0.85+ 가 `component View(...)` Flow 문법을 채택해
 * `Libraries/Components/View/View.js` 등이 이 경로로 처리된다.
 */
describe("bundle: Flow component syntax resolves React namespace import", () => {
  test("React.forwardRef generated by flow component wrapper gets renamed", async () => {
    const fixture = await createFixture({
      "entry.js": `
        /* @flow */
        import * as React from 'react';

        component MyBox(
          ref?: mixed,
          ...props: { label?: string }
        ) {
          return null;
        }

        module.exports = MyBox;
      `,
      "node_modules/react/package.json": JSON.stringify({
        name: "react",
        main: "index.js",
      }),
      "node_modules/react/index.js": `
        module.exports = { forwardRef: function(fn) { return fn; } };
      `,
    });

    try {
      const entry = resolve(fixture.dir, "entry.js");
      const proc = Bun.spawnSync([
        ZTS_BIN,
        "--bundle",
        "--platform=react-native",
        "--rn-platform=ios",
        "--flow",
        entry,
      ]);
      expect(proc.exitCode).toBe(0);
      const output = proc.stdout.toString();

      // forwardRef 호출 자체는 emit 되어야 한다.
      expect(output).toMatch(/\.forwardRef\s*\(/);

      // 버그 시: `React` identifier 의 symbol_id 가 해석되지 않아 bundle 에서 hoisted var
      // 선언에 React 가 빠지고 `React.forwardRef(...)` 만 남아 runtime ReferenceError.
      // 수정 후: React 가 반드시 binding 으로 선언 (`var React`, `var ..., React, ...`
      // 또는 renamed 형태) 되거나 `__toESM(require_react_index())` 로 초기화된다.
      // bundle 내에서 forwardRef 를 호출하는 identifier 가 실제로 declared 인지 검증.
      // regex: `X = Y.forwardRef(...)` 에서 Y 를 추출 → 해당 identifier 가 bundle 어디서든
      // `var` 또는 assignment 로 선언되어야 한다.
      const forwardRefCallers = new Set<string>();
      for (const m of output.matchAll(/(?:^|[=\s,(])([A-Za-z_$][\w$]*)\.forwardRef\s*\(/g)) {
        forwardRefCallers.add(m[1]);
      }
      expect(forwardRefCallers.size).toBeGreaterThan(0);
      for (const name of forwardRefCallers) {
        const declRe = new RegExp(`(?:\\bvar\\b[^;]*\\b${name}\\b|\\b${name}\\s*=\\s*[^=])`);
        expect(output).toMatch(declRe);
      }
    } finally {
      await fixture.cleanup();
    }
  });
});
