export {
  DEFAULT_RN_ENTRY,
  DEFAULT_RN_PLATFORM,
  PACKAGE_MANAGERS,
  createReactNativeConfig,
  detectPackageManager,
  initReactNativeProject,
  planReactNativeInit,
  type FileChange,
  type InitReactNativeOptions,
  type InitReactNativeResult,
  type PackageManager,
  type PlannedFile,
  type ReactNativePlatform,
} from './react-native.ts';
