import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

export type ReactNativePlatform = 'ios' | 'android';

export const PACKAGE_MANAGERS = ['bun', 'npm', 'pnpm', 'yarn'] as const;
export type PackageManager = (typeof PACKAGE_MANAGERS)[number];

export interface InitReactNativeOptions {
  root?: string;
  defaultPlatform?: ReactNativePlatform;
  dryRun?: boolean;
  force?: boolean;
  metroFallback?: boolean;
  packageManager?: PackageManager;
  zntcVersion?: string;
}

export interface PlannedFile {
  path: string;
  before: string | null;
  after: string;
  changed: boolean;
}

export interface FileChange {
  path: string;
  action: 'create' | 'update' | 'unchanged';
}

export interface InitReactNativeResult {
  root: string;
  changes: FileChange[];
  dryRun: boolean;
  installCommand: string;
}

const PACKAGE_JSON = 'package.json';
const ZNTC_CONFIG = 'zntc.config.ts';

export const DEFAULT_RN_ENTRY = 'index.js';
export const DEFAULT_RN_PLATFORM: ReactNativePlatform = 'ios';

const DEFAULT_ZNTC_VERSION = 'latest';

function readText(path: string): string | null {
  try {
    return readFileSync(path, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

function formatJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function parsePackageJson(raw: string): Record<string, any> {
  try {
    return JSON.parse(raw);
  } catch (error) {
    throw new Error(
      `failed to parse ${PACKAGE_JSON}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

function hasReactNativeDependency(pkg: Record<string, any>): boolean {
  return Boolean(pkg.dependencies?.['react-native'] ?? pkg.devDependencies?.['react-native']);
}

function ensureObject(value: unknown): Record<string, any> {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    return value as Record<string, any>;
  }
  return {};
}

function bundleOut(platform: ReactNativePlatform): string {
  return platform === 'ios'
    ? '--bundle-output ios/main.jsbundle --assets-dest ios'
    : '--bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res';
}

function zntcBundleScript(platform: ReactNativePlatform): string {
  return `zntc --bundle ${DEFAULT_RN_ENTRY} --platform=react-native --rn-platform=${platform} ${bundleOut(platform)}`;
}

function metroBundleScript(platform: ReactNativePlatform): string {
  return `react-native bundle --platform ${platform} --dev false --entry-file ${DEFAULT_RN_ENTRY} ${bundleOut(platform)}`;
}

function patchPackageJson(
  pkg: Record<string, any>,
  options: Required<
    Pick<InitReactNativeOptions, 'defaultPlatform' | 'metroFallback' | 'zntcVersion'>
  >,
): Record<string, any> {
  const next = { ...pkg };
  const scripts = { ...ensureObject(next.scripts) };
  const dependencies = ensureObject(next.dependencies);
  const devDependencies = { ...ensureObject(next.devDependencies) };

  if (!dependencies['@zntc/core'] && !devDependencies['@zntc/core']) {
    devDependencies['@zntc/core'] = options.zntcVersion;
  }
  if (!dependencies['@zntc/react-native'] && !devDependencies['@zntc/react-native']) {
    devDependencies['@zntc/react-native'] = options.zntcVersion;
  }

  const zntcStart = `zntc dev --platform=react-native --rn-platform=${options.defaultPlatform} ${DEFAULT_RN_ENTRY}`;
  const previousStart = typeof scripts.start === 'string' ? scripts.start : undefined;
  if (options.metroFallback && previousStart && previousStart !== zntcStart) {
    scripts['start:metro'] = scripts['start:metro'] ?? previousStart;
  }

  scripts.start = zntcStart;
  scripts['start:zntc'] = scripts['start:zntc'] ?? zntcStart;
  scripts['bundle:ios'] = scripts['bundle:ios'] ?? zntcBundleScript('ios');
  scripts['bundle:android'] = scripts['bundle:android'] ?? zntcBundleScript('android');

  if (options.metroFallback) {
    scripts['bundle:metro:ios'] = scripts['bundle:metro:ios'] ?? metroBundleScript('ios');
    scripts['bundle:metro:android'] =
      scripts['bundle:metro:android'] ?? metroBundleScript('android');
  }

  next.scripts = scripts;
  if (Object.keys(devDependencies).length > 0 || next.devDependencies !== undefined) {
    next.devDependencies = devDependencies;
  }
  return next;
}

export function createReactNativeConfig(): string {
  return `// ZNTC dev server + bundler config for React Native CLI.
// Generated by @zntc/init.

import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export default {
  root: __dirname,
  entry: "${DEFAULT_RN_ENTRY}",
  dev: true,
  minify: false,
  transformer: {
    babel: {},
  },
  serializer: {
    polyfills: [],
    prelude: [],
  },
  server: {
    port: 8081,
    host: "localhost",
    useGlobalHotkey: true,
    forwardClientLogs: false,
  },
};
`;
}

function planPackageJson(
  root: string,
  options: Required<
    Pick<InitReactNativeOptions, 'defaultPlatform' | 'metroFallback' | 'zntcVersion'>
  >,
): PlannedFile {
  const path = join(root, PACKAGE_JSON);
  const before = readText(path);
  if (before === null) {
    throw new Error(`package.json not found in ${root}`);
  }
  const pkg = parsePackageJson(before);
  if (!hasReactNativeDependency(pkg)) {
    throw new Error(
      'react-native dependency not found; @zntc/init currently supports React Native CLI projects only',
    );
  }
  const after = formatJson(patchPackageJson(pkg, options));
  return { path, before, after, changed: before !== after };
}

function planConfig(root: string, force: boolean): PlannedFile {
  const path = join(root, ZNTC_CONFIG);
  const before = readText(path);
  const after = before !== null && !force ? before : createReactNativeConfig();
  return { path, before, after, changed: before !== after };
}

export function planReactNativeInit(options: InitReactNativeOptions = {}): PlannedFile[] {
  const root = resolve(options.root ?? process.cwd());
  const force = options.force ?? false;
  const normalized = {
    defaultPlatform: options.defaultPlatform ?? DEFAULT_RN_PLATFORM,
    metroFallback: options.metroFallback ?? true,
    zntcVersion: options.zntcVersion ?? DEFAULT_ZNTC_VERSION,
  };

  if (normalized.defaultPlatform !== 'ios' && normalized.defaultPlatform !== 'android') {
    throw new Error(`unsupported default platform: ${normalized.defaultPlatform}`);
  }

  return [planPackageJson(root, normalized), planConfig(root, force)];
}

export function detectPackageManager(root: string): PackageManager {
  if (existsSync(join(root, 'bun.lock')) || existsSync(join(root, 'bun.lockb'))) return 'bun';
  if (existsSync(join(root, 'pnpm-lock.yaml'))) return 'pnpm';
  if (existsSync(join(root, 'yarn.lock'))) return 'yarn';

  const rawPackageJson = readText(join(root, PACKAGE_JSON));
  if (rawPackageJson) {
    try {
      const packageManager = JSON.parse(rawPackageJson).packageManager;
      if (typeof packageManager === 'string') {
        for (const pm of PACKAGE_MANAGERS) {
          if (packageManager.startsWith(`${pm}@`)) return pm;
        }
      }
    } catch {}
  }

  return 'npm';
}

function installCommand(pm: PackageManager): string {
  return `${pm} install`;
}

function toChange(file: PlannedFile): FileChange {
  if (!file.changed) return { path: file.path, action: 'unchanged' };
  return { path: file.path, action: file.before === null ? 'create' : 'update' };
}

export function initReactNativeProject(
  options: InitReactNativeOptions = {},
): InitReactNativeResult {
  const root = resolve(options.root ?? process.cwd());
  const planned = planReactNativeInit({ ...options, root });
  const dryRun = options.dryRun ?? false;

  if (!dryRun) {
    for (const file of planned) {
      if (!file.changed) continue;
      mkdirSync(dirname(file.path), { recursive: true });
      writeFileSync(file.path, file.after);
    }
  }

  const pm = options.packageManager ?? detectPackageManager(root);
  return {
    root,
    changes: planned.map(toChange),
    dryRun,
    installCommand: installCommand(pm),
  };
}
