import { join, resolve } from 'node:path';

import {
  DEFAULT_ZNTC_VERSION,
  PACKAGE_JSON,
  ZNTC_CONFIG,
  addDevDependency,
  applyPlan,
  ensureObject,
  formatJson,
  hasAnyDependency,
  parsePackageJson,
  readText,
  type FileChange,
  type PackageManager,
  type PlannedFile,
} from './shared.ts';

export type ReactNativePlatform = 'ios' | 'android';

export interface InitReactNativeOptions {
  root?: string;
  defaultPlatform?: ReactNativePlatform;
  dryRun?: boolean;
  force?: boolean;
  metroFallback?: boolean;
  packageManager?: PackageManager;
  zntcVersion?: string;
}

export interface InitReactNativeResult {
  root: string;
  changes: FileChange[];
  dryRun: boolean;
  installCommand: string;
}

export const DEFAULT_RN_ENTRY = 'index.js';
export const DEFAULT_RN_PLATFORM: ReactNativePlatform = 'ios';

function bundleOut(platform: ReactNativePlatform): string {
  return platform === 'ios'
    ? '--bundle-output ios/main.jsbundle --assets-dest ios'
    : '--bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res';
}

function zntcBundleScript(platform: ReactNativePlatform): string {
  // Metro 의 `react-native bundle --dev false` 가 minify 를 자동 활성하는 동작과 parity.
  // RN 사용자가 `bun run bundle:ios` 했을 때 ~2배 큰 비-minify bundle 받는 사고 차단.
  return `zntc --bundle ${DEFAULT_RN_ENTRY} --platform=react-native --rn-platform=${platform} --minify ${bundleOut(platform)}`;
}

function metroBundleScript(platform: ReactNativePlatform): string {
  return `react-native bundle --platform ${platform} --dev false --entry-file ${DEFAULT_RN_ENTRY} ${bundleOut(platform)}`;
}

function patchPackageJson(
  pkg: Record<string, any>,
  options: Required<
    Pick<InitReactNativeOptions, 'defaultPlatform' | 'metroFallback' | 'zntcVersion'>
  >,
): Record<string, any> {
  let next = addDevDependency(pkg, '@zntc/core', options.zntcVersion);
  next = addDevDependency(next, '@zntc/react-native', options.zntcVersion);

  const scripts = { ...ensureObject(next.scripts) };
  const zntcStart = `zntc dev --platform=react-native --rn-platform=${options.defaultPlatform} ${DEFAULT_RN_ENTRY}`;
  const previousStart = typeof scripts.start === 'string' ? scripts.start : undefined;
  if (options.metroFallback && previousStart && previousStart !== zntcStart) {
    scripts['start:metro'] = scripts['start:metro'] ?? previousStart;
  }

  scripts.start = zntcStart;
  scripts['start:zntc'] = scripts['start:zntc'] ?? zntcStart;
  scripts['bundle:ios'] = scripts['bundle:ios'] ?? zntcBundleScript('ios');
  scripts['bundle:android'] = scripts['bundle:android'] ?? zntcBundleScript('android');

  if (options.metroFallback) {
    scripts['bundle:metro:ios'] = scripts['bundle:metro:ios'] ?? metroBundleScript('ios');
    scripts['bundle:metro:android'] =
      scripts['bundle:metro:android'] ?? metroBundleScript('android');
  }

  return { ...next, scripts };
}

export function createReactNativeConfig(): string {
  return `// ZNTC dev server + bundler config for React Native CLI.
// Generated by @zntc/init.

import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export default {
  root: __dirname,
  entry: "${DEFAULT_RN_ENTRY}",
  dev: true,
  minify: false,
  transformer: {
    babel: {},
  },
  serializer: {
    polyfills: [],
    prelude: [],
  },
  server: {
    port: 8081,
    host: "localhost",
    useGlobalHotkey: true,
    forwardClientLogs: true,
  },
};
`;
}

function planPackageJson(
  root: string,
  options: Required<
    Pick<InitReactNativeOptions, 'defaultPlatform' | 'metroFallback' | 'zntcVersion'>
  >,
): PlannedFile {
  const path = join(root, PACKAGE_JSON);
  const before = readText(path);
  if (before === null) {
    throw new Error(`package.json not found in ${root}`);
  }
  const pkg = parsePackageJson(before);
  if (!hasAnyDependency(pkg, ['react-native'])) {
    throw new Error(
      'react-native dependency not found; use `zntc-init vite|rspack|web` for non-RN projects',
    );
  }
  const after = formatJson(patchPackageJson(pkg, options));
  return { path, before, after, changed: before !== after };
}

function planConfig(root: string, force: boolean): PlannedFile {
  const path = join(root, ZNTC_CONFIG);
  const before = readText(path);
  const after = before !== null && !force ? before : createReactNativeConfig();
  return { path, before, after, changed: before !== after };
}

export function planReactNativeInit(options: InitReactNativeOptions = {}): PlannedFile[] {
  const root = resolve(options.root ?? process.cwd());
  const force = options.force ?? false;
  const normalized = {
    defaultPlatform: options.defaultPlatform ?? DEFAULT_RN_PLATFORM,
    metroFallback: options.metroFallback ?? true,
    zntcVersion: options.zntcVersion ?? DEFAULT_ZNTC_VERSION,
  };

  if (normalized.defaultPlatform !== 'ios' && normalized.defaultPlatform !== 'android') {
    throw new Error(`unsupported default platform: ${normalized.defaultPlatform}`);
  }

  return [planPackageJson(root, normalized), planConfig(root, force)];
}

export function initReactNativeProject(
  options: InitReactNativeOptions = {},
): InitReactNativeResult {
  const root = resolve(options.root ?? process.cwd());
  const planned = planReactNativeInit({ ...options, root });
  return applyPlan({
    root,
    planned,
    dryRun: options.dryRun ?? false,
    packageManager: options.packageManager,
  });
}
