import { join, resolve } from 'node:path';

import {
  DEFAULT_ZNTC_VERSION,
  PACKAGE_JSON,
  addDevDependency,
  applyPlan,
  formatJson,
  hasAnyDependency,
  parsePackageJson,
  planOverlayConfig,
  readText,
  type ApplyPlanResult,
  type FileChange,
  type PackageManager,
  type PlannedFile,
} from './shared.ts';

export type RspackBundler = 'rspack' | 'webpack';

export interface InitRspackOptions {
  root?: string;
  dryRun?: boolean;
  force?: boolean;
  packageManager?: PackageManager;
  zntcVersion?: string;
  /** 강제로 bundler 종류를 지정 (default: package.json 으로 자동 추론) */
  bundler?: RspackBundler;
}

export interface InitRspackResult {
  root: string;
  changes: FileChange[];
  dryRun: boolean;
  installCommand: string;
  bundler: RspackBundler;
}

const CONFIG_CANDIDATES: Record<RspackBundler, readonly string[]> = {
  rspack: ['rspack.config.ts', 'rspack.config.mts', 'rspack.config.js', 'rspack.config.mjs'],
  webpack: ['webpack.config.ts', 'webpack.config.mts', 'webpack.config.js', 'webpack.config.mjs'],
};

const DEFAULT_CONFIG_NAME: Record<RspackBundler, string> = {
  rspack: 'rspack.config.mjs',
  webpack: 'webpack.config.mjs',
};

export function createRspackConfig(bundler: RspackBundler): string {
  const header =
    bundler === 'rspack'
      ? '// Generated by @zntc/init — Rspack with @zntc/rspack-loader (replaces swc-loader / esbuild-loader).'
      : '// Generated by @zntc/init — Webpack 5 with @zntc/rspack-loader (replaces babel-loader / swc-loader).';
  return `${header}
export default {
  module: {
    rules: [
      {
        test: /\\.(?:tsx?|jsx?)$/,
        exclude: /node_modules/,
        loader: '@zntc/rspack-loader',
        options: {
          transpileOptions: { target: 'es2020', jsx: 'automatic' },
        },
      },
    ],
  },
};
`;
}

function detectBundler(pkg: Record<string, any>, hint?: RspackBundler): RspackBundler {
  if (hint) return hint;
  if (hasAnyDependency(pkg, ['@rspack/core', '@rspack/cli'])) return 'rspack';
  if (hasAnyDependency(pkg, ['webpack', 'webpack-cli'])) return 'webpack';
  throw new Error(
    '@rspack/core or webpack dependency not found; install one of them first or pass --bundler',
  );
}

function planPackageJson(
  root: string,
  zntcVersion: string,
  hint?: RspackBundler,
): { plan: PlannedFile; bundler: RspackBundler } {
  const path = join(root, PACKAGE_JSON);
  const before = readText(path);
  if (before === null) {
    throw new Error(`package.json not found in ${root}`);
  }
  const pkg = parsePackageJson(before);
  const bundler = detectBundler(pkg, hint);
  let next = addDevDependency(pkg, '@zntc/core', zntcVersion);
  next = addDevDependency(next, '@zntc/rspack-loader', zntcVersion);
  const after = formatJson(next);
  return { plan: { path, before, after, changed: before !== after }, bundler };
}

function manualPatch(bundler: RspackBundler): string {
  const product = bundler === 'rspack' ? 'rspack.config' : 'webpack.config';
  return [
    `Add the ZNTC loader to your existing ${product}:`,
    '',
    '  module: {',
    '    rules: [',
    '      {',
    '        test: /\\.(?:tsx?|jsx?)$/,',
    '        exclude: /node_modules/,',
    "        loader: '@zntc/rspack-loader',",
    "        options: { transpileOptions: { target: 'es2020', jsx: 'automatic' } },",
    '      },',
    '    ],',
    '  },',
    '',
    'Re-run with --force to overwrite the existing config instead.',
  ].join('\n');
}

export function planRspackInit(options: InitRspackOptions = {}): {
  files: PlannedFile[];
  bundler: RspackBundler;
} {
  const root = resolve(options.root ?? process.cwd());
  const zntcVersion = options.zntcVersion ?? DEFAULT_ZNTC_VERSION;
  const force = options.force ?? false;
  const { plan: pkgPlan, bundler } = planPackageJson(root, zntcVersion, options.bundler);
  const configPlan = planOverlayConfig({
    root,
    candidates: CONFIG_CANDIDATES[bundler],
    defaultName: DEFAULT_CONFIG_NAME[bundler],
    generate: () => createRspackConfig(bundler),
    manualInstructions: manualPatch(bundler),
    force,
  });
  return { files: [pkgPlan, configPlan], bundler };
}

export function initRspackProject(options: InitRspackOptions = {}): InitRspackResult {
  const root = resolve(options.root ?? process.cwd());
  const { files: planned, bundler } = planRspackInit({ ...options, root });
  const applied: ApplyPlanResult = applyPlan({
    root,
    planned,
    dryRun: options.dryRun ?? false,
    packageManager: options.packageManager,
  });
  return { ...applied, bundler };
}
