import { join, resolve } from 'node:path';

import {
  DEFAULT_ZNTC_VERSION,
  PACKAGE_JSON,
  addDevDependency,
  applyPlan,
  formatJson,
  hasAnyDependency,
  parsePackageJson,
  planOverlayConfig,
  readText,
  type FileChange,
  type PackageManager,
  type PlannedFile,
} from './shared.ts';

export interface InitViteOptions {
  root?: string;
  dryRun?: boolean;
  force?: boolean;
  packageManager?: PackageManager;
  zntcVersion?: string;
}

export interface InitViteResult {
  root: string;
  changes: FileChange[];
  dryRun: boolean;
  installCommand: string;
}

const VITE_CONFIG_CANDIDATES = [
  'vite.config.ts',
  'vite.config.mts',
  'vite.config.js',
  'vite.config.mjs',
];

const DEFAULT_VITE_CONFIG = 'vite.config.ts';

export function createViteConfig(): string {
  return `// Generated by @zntc/init — replaces Vite의 esbuild transform 을 ZNTC 로.
import { defineConfig } from 'vite';
import { zntc } from '@zntc/vite-plugin';

export default defineConfig({
  plugins: [zntc()],
  esbuild: false,
});
`;
}

function planPackageJson(root: string, zntcVersion: string): PlannedFile {
  const path = join(root, PACKAGE_JSON);
  const before = readText(path);
  if (before === null) {
    throw new Error(`package.json not found in ${root}`);
  }
  const pkg = parsePackageJson(before);
  if (!hasAnyDependency(pkg, ['vite'])) {
    throw new Error(
      'vite dependency not found; install Vite first, or use `zntc-init web` for a standalone setup',
    );
  }
  let next = addDevDependency(pkg, '@zntc/core', zntcVersion);
  next = addDevDependency(next, '@zntc/vite-plugin', zntcVersion);
  const after = formatJson(next);
  return { path, before, after, changed: before !== after };
}

const MANUAL_PATCH = [
  'Add ZNTC to your existing vite.config:',
  '',
  "  import { zntc } from '@zntc/vite-plugin';",
  '',
  '  export default defineConfig({',
  '    plugins: [zntc()],   // 기존 plugins 배열에 합쳐 주세요',
  '    esbuild: false,      // ZNTC 가 .ts/.tsx/.jsx 변환을 담당',
  '  });',
  '',
  'Re-run with --force to overwrite the existing config instead.',
].join('\n');

export function planViteInit(options: InitViteOptions = {}): PlannedFile[] {
  const root = resolve(options.root ?? process.cwd());
  const zntcVersion = options.zntcVersion ?? DEFAULT_ZNTC_VERSION;
  const force = options.force ?? false;
  return [
    planPackageJson(root, zntcVersion),
    planOverlayConfig({
      root,
      candidates: VITE_CONFIG_CANDIDATES,
      defaultName: DEFAULT_VITE_CONFIG,
      generate: createViteConfig,
      manualInstructions: MANUAL_PATCH,
      force,
    }),
  ];
}

export function initViteProject(options: InitViteOptions = {}): InitViteResult {
  const root = resolve(options.root ?? process.cwd());
  const planned = planViteInit({ ...options, root });
  return applyPlan({
    root,
    planned,
    dryRun: options.dryRun ?? false,
    packageManager: options.packageManager,
  });
}
