import './build-plugins/basic-hooks';
import './build-plugins/plugin-context';
import './build-plugins/module-meta';
import './build-plugins/plugin-resolve';
import './build-plugins/transform-tree-shaking';
import './build-plugins/resolve-context';
import './build-plugins/build-sync';
import './build-plugins/diagnostics';
import './build-plugins/lifecycle';
