
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @flow
 *
 * @generated by codegen project: GenerateViewConfigJs.js
 */

'use strict';

const NativeComponentRegistry = require('react-native/Libraries/NativeComponent/NativeComponentRegistry');
const {ConditionallyIgnoredEventHandlers} = require('react-native/Libraries/NativeComponent/ViewConfigIgnore');

let nativeComponentName = 'RNSBottomTabsScreen';
export const __INTERNAL_VIEW_CONFIG = {
  uiViewClassName: "RNSBottomTabsScreen",
  directEventTypes: {
    topLifecycleStateChange: {
      registrationName: "onLifecycleStateChange"
    },
    topWillAppear: {
      registrationName: "onWillAppear"
    },
    topDidAppear: {
      registrationName: "onDidAppear"
    },
    topWillDisappear: {
      registrationName: "onWillDisappear"
    },
    topDidDisappear: {
      registrationName: "onDidDisappear"
    }
  },
  validAttributes: {
    isFocused: true,
    tabKey: true,
    title: true,
    isTitleUndefined: true,
    badgeValue: true,
    tabBarItemTestID: true,
    tabBarItemAccessibilityLabel: true,
    orientation: true,
    drawableIconResourceName: true,
    imageIconResource: {
      process: (req => 'default' in req ? req.default : req)(require('react-native/Libraries/Image/resolveAssetSource'))
    },
    tabBarItemBadgeTextColor: require('react-native/Libraries/Components/View/ReactNativeStyleAttributes').colorAttribute,
    tabBarItemBadgeBackgroundColor: require('react-native/Libraries/Components/View/ReactNativeStyleAttributes').colorAttribute,
    standardAppearance: true,
    scrollEdgeAppearance: true,
    iconType: true,
    iconImageSource: {
      process: (req => 'default' in req ? req.default : req)(require('react-native/Libraries/Image/resolveAssetSource'))
    },
    iconResourceName: true,
    selectedIconImageSource: {
      process: (req => 'default' in req ? req.default : req)(require('react-native/Libraries/Image/resolveAssetSource'))
    },
    selectedIconResourceName: true,
    systemItem: true,
    specialEffects: true,
    overrideScrollViewContentInsetAdjustmentBehavior: true,
    bottomScrollEdgeEffect: true,
    leftScrollEdgeEffect: true,
    rightScrollEdgeEffect: true,
    topScrollEdgeEffect: true,
    userInterfaceStyle: true,
    ...ConditionallyIgnoredEventHandlers({
      onLifecycleStateChange: true,
      onWillAppear: true,
      onDidAppear: true,
      onWillDisappear: true,
      onDidDisappear: true
    })
  }
};
export default NativeComponentRegistry.get(nativeComponentName, () => __INTERNAL_VIEW_CONFIG);
