/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @flow
 *
 * @generated by codegen project: GenerateViewConfigJs.js
 */

'use strict';

const NativeComponentRegistry = require('react-native/Libraries/NativeComponent/NativeComponentRegistry');
const {
  ConditionallyIgnoredEventHandlers,
} = require('react-native/Libraries/NativeComponent/ViewConfigIgnore');

let nativeComponentName = 'RNSScreenStackHeaderConfig';
export const __INTERNAL_VIEW_CONFIG = {
  uiViewClassName: 'RNSScreenStackHeaderConfig',
  directEventTypes: {
    topAttached: {
      registrationName: 'onAttached',
    },
    topDetached: {
      registrationName: 'onDetached',
    },
    topPressHeaderBarButtonItem: {
      registrationName: 'onPressHeaderBarButtonItem',
    },
    topPressHeaderBarButtonMenuItem: {
      registrationName: 'onPressHeaderBarButtonMenuItem',
    },
  },
  validAttributes: {
    backgroundColor: require('react-native/Libraries/Components/View/ReactNativeStyleAttributes')
      .colorAttribute,
    backTitle: true,
    backTitleFontFamily: true,
    backTitleFontSize: true,
    backTitleVisible: true,
    color: require('react-native/Libraries/Components/View/ReactNativeStyleAttributes')
      .colorAttribute,
    direction: true,
    hidden: true,
    hideShadow: true,
    largeTitle: true,
    largeTitleFontFamily: true,
    largeTitleFontSize: true,
    largeTitleFontWeight: true,
    largeTitleBackgroundColor:
      require('react-native/Libraries/Components/View/ReactNativeStyleAttributes').colorAttribute,
    largeTitleHideShadow: true,
    largeTitleColor: require('react-native/Libraries/Components/View/ReactNativeStyleAttributes')
      .colorAttribute,
    translucent: true,
    title: true,
    titleFontFamily: true,
    titleFontSize: true,
    titleFontWeight: true,
    titleColor: require('react-native/Libraries/Components/View/ReactNativeStyleAttributes')
      .colorAttribute,
    disableBackButtonMenu: true,
    backButtonDisplayMode: true,
    hideBackButton: true,
    backButtonInCustomView: true,
    blurEffect: true,
    topInsetEnabled: true,
    headerLeftBarButtonItems: true,
    headerRightBarButtonItems: true,
    synchronousShadowStateUpdatesEnabled: true,
    userInterfaceStyle: true,
    ...ConditionallyIgnoredEventHandlers({
      onAttached: true,
      onDetached: true,
      onPressHeaderBarButtonItem: true,
      onPressHeaderBarButtonMenuItem: true,
    }),
  },
};
export default NativeComponentRegistry.get(nativeComponentName, () => __INTERNAL_VIEW_CONFIG);
