/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @flow
 *
 * @generated by codegen project: GenerateViewConfigJs.js
 */

'use strict';

const NativeComponentRegistry = require('react-native/Libraries/NativeComponent/NativeComponentRegistry');
const {
  ConditionallyIgnoredEventHandlers,
} = require('react-native/Libraries/NativeComponent/ViewConfigIgnore');

let nativeComponentName = 'RNSScreen';
export const __INTERNAL_VIEW_CONFIG = {
  uiViewClassName: 'RNSScreen',
  directEventTypes: {
    topAppear: {
      registrationName: 'onAppear',
    },
    topDisappear: {
      registrationName: 'onDisappear',
    },
    topDismissed: {
      registrationName: 'onDismissed',
    },
    topNativeDismissCancelled: {
      registrationName: 'onNativeDismissCancelled',
    },
    topWillAppear: {
      registrationName: 'onWillAppear',
    },
    topWillDisappear: {
      registrationName: 'onWillDisappear',
    },
    topHeaderHeightChange: {
      registrationName: 'onHeaderHeightChange',
    },
    topTransitionProgress: {
      registrationName: 'onTransitionProgress',
    },
    topGestureCancel: {
      registrationName: 'onGestureCancel',
    },
    topHeaderBackButtonClicked: {
      registrationName: 'onHeaderBackButtonClicked',
    },
    topSheetDetentChanged: {
      registrationName: 'onSheetDetentChanged',
    },
  },
  validAttributes: {
    screenId: true,
    sheetAllowedDetents: true,
    sheetLargestUndimmedDetent: true,
    sheetGrabberVisible: true,
    sheetCornerRadius: true,
    sheetExpandsWhenScrolledToEdge: true,
    sheetInitialDetent: true,
    sheetElevation: true,
    sheetShouldOverflowTopInset: true,
    sheetDefaultResizeAnimationEnabled: true,
    customAnimationOnSwipe: true,
    fullScreenSwipeEnabled: true,
    fullScreenSwipeShadowEnabled: true,
    homeIndicatorHidden: true,
    preventNativeDismiss: true,
    gestureEnabled: true,
    statusBarColor: require('react-native/Libraries/Components/View/ReactNativeStyleAttributes')
      .colorAttribute,
    statusBarHidden: true,
    screenOrientation: true,
    statusBarAnimation: true,
    statusBarStyle: true,
    statusBarTranslucent: true,
    gestureResponseDistance: true,
    stackPresentation: true,
    stackAnimation: true,
    transitionDuration: true,
    replaceAnimation: true,
    swipeDirection: true,
    hideKeyboardOnSwipe: true,
    activityState: true,
    navigationBarColor: require('react-native/Libraries/Components/View/ReactNativeStyleAttributes')
      .colorAttribute,
    navigationBarTranslucent: true,
    navigationBarHidden: true,
    nativeBackButtonDismissalEnabled: true,
    bottomScrollEdgeEffect: true,
    leftScrollEdgeEffect: true,
    rightScrollEdgeEffect: true,
    topScrollEdgeEffect: true,
    synchronousShadowStateUpdatesEnabled: true,
    androidResetScreenShadowStateOnOrientationChangeEnabled: true,
    ...ConditionallyIgnoredEventHandlers({
      onAppear: true,
      onDisappear: true,
      onDismissed: true,
      onNativeDismissCancelled: true,
      onWillAppear: true,
      onWillDisappear: true,
      onHeaderHeightChange: true,
      onTransitionProgress: true,
      onGestureCancel: true,
      onHeaderBackButtonClicked: true,
      onSheetDetentChanged: true,
    }),
  },
};
export default NativeComponentRegistry.get(nativeComponentName, () => __INTERNAL_VIEW_CONFIG);
